---
- name: install bild app
  hosts: slave1
  become: yes

  tasks:
    - name: Ensure maven is present
      apt:
        name: maven
        state: present

    - name: Ensure git is present
      apt:
        name: git
        state: present

- name: ckeck app
  git:
    repo: https://github.com/boxfuse/boxfuse-sample-java-war-hello.git
    dest: /home/

- name: bild code
  shell: "cd /home && mvn package"

- name: install prod app
  hosts: slave2
  become: yes

  tasks:
    - name: Ensure tomcat9 is present
      apt:
        name: tomcat9
        state: present

- name: copy file
  synchronize:
    src: /target/hello-1.0.war
    dest: /var/lib/tomcat9/webapps/
  delegate_to: 20.67.26.83