---
- name: install maven
  hosts: sbor
  become: yes

  tasks:
  - name: ensure mvn package is presents
    apt:
     name: maven
     state: present

- name: install java
  hosts: sbor
  become: yes

  tasks:
  - name: Ensure java package is present
    apt:
     name: default-jdk
     state: present

- name: install git
  hosts: sbor
  become: yes

  tasks:
  - name: Ensure git package is present
    apt:
     name: git
     state: present

  - name: git repo
    git: https://github.com/boxfuse/boxfuse-sample-java-war-hello.git
     repo: /home/

  - name: cp bild code
     copy:
      src: hello-1.0.war
      dest: /home
       shell: "mvn package"

- name: install tomcat9
  hosts: prod
  become: yes

  tasks:
  - name: install tomacat9
    apt:
      name: tomcat9
      state: present

  - name: start war file
    dest: /home
