---
# tasks file for webserver

- name: ensure war file in slave2
  hosts: slave2
  become: yes

  tasks:
    - name: war file to master
      synchronize:
        mode: push
        src: /tmp/hello-1.0.war
        dest: /var/lib/tomcat9/webapps/
      delegate_to: 127.0.0.1